cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      logged_in: true
      name: John Smith
      password: $2b$12$ZnVcxalC1DH7AifSl/SXoeOcwkpPqjENLn6BEDF/BZ5wW5vgqQqBy
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$jBI.Nj2LT32wZ37JxKqODOj3Mi3Pf6NJXyEoe1yfq/Y2CgWzNIV06
preauthorized:
  emails:
  - melsby@gmail.com
