cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    mike:
      email: e@mail.com
      logged_in: false
      name: Michael
      password: $2b$12$XUE1Kql4BmW2QY892VI7O.xwqoPHcasJ2HM2HOtAFgEXnrByA81E2
preauthorized:
  emails:
  - melsby@gmail.com
